accounts/urls.py
from django.urls import path
from accounts import views as accounts_views
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('register/', accounts_views.register, name='register'),
]

core/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('dashboard', views.dashboard, name='dashboard'),
    path('contact', views.contact, name='contact'),
    path('dashboard/edit-task/<str:id>/', views.edit_task, name='edit_task'),
    path('dashboard/delete-task/<str:id>/', views.delete_task, name='delete_task'),
]

manager/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('accounts.urls', 'accounts'), namespace='accounts')),
    path('', include(('core.urls', 'core'), namespace='core'))
]

accounts/models.py
from django.db import models

# Create your models here.

core/models.py
from django.contrib.auth.models import User
from django.db import models
from taggit.managers import TaggableManager
from datetime import date

class Task(models.Model):
    user = models.ForeignKey(User, null=True, on_delete=models.CASCADE)
    title = models.CharField(max_length=500)
    tags = TaggableManager()
    due_date = models.DateField()
    is_complete = models.BooleanField(default=False)

    class Meta:
        '''
        Meta class to order taks.
        '''
        ordering = ['-due_date']

    def __str__(self):
        '''
        String method returning self.title.
        '''
        return self.title

    @property
    def is_past_due(self):
        '''
        Propety to check if the date is past.
        '''
        if date.today() > self.due_date:
            return True
        return False

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class RegisterForm(UserCreationForm):

    email = forms.EmailField(label='E-mail')

    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError('There is someone using this email')
        return email

    def save(self, commit=True):
        user = super(RegisterForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user

core/forms.py
from django import forms
from core.models import Task

class TaskForm(forms.ModelForm):
    '''
    Task Form inherits from Django Model Form.

    Fields are: ['due_date', 'title', 'tags']
    '''
    class Meta:
            model = Task
            fields = ['due_date', 'title', 'tags']
            exclude = ('user',)
            widgets = {
            'due_date': forms.TextInput(attrs={
                'id':'flatpickr',
                'placeholder':'Due date',
            }),
            'title': forms.TextInput(attrs={
            	'placeholder':'Task to be done'
            	}),
            'tags': forms.TextInput(attrs={
            	'placeholder':'Eg.: python, django, views'
            	}),
            }

class TaskEditForm(forms.ModelForm):
    '''
    Inherits from Django Model Form

    Fields are: ['due_date', 'title, 'is_complete']
    '''
    class Meta:
            model = Task
            fields = ['due_date', 'title', 'is_complete']
            exclude = ('user', 'tags')
            widgets = {
            'due_date': forms.TextInput(attrs={
                'id':'flatpickr',
                'placeholder':'Due date',
            }),
            'title': forms.TextInput(attrs={
                'placeholder':'Task to be done'
                }),
            }

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login
from django.conf import settings

from .forms import RegisterForm

def register(request):
    """
    Login view.

    ``User``
        An instance of User Model.
    """
    template_name = 'registration/register.html'
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save()
            user = authenticate(
                username=user.username, password=form.cleaned_data['password1']
            )
            login(request, user)
            return redirect('core:home')
    else:
        form = RegisterForm()
    context = {
        'form': form
    }
    return render(request, template_name, context)

core/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from .models import Task
from django.contrib.auth.models import User
from .forms import TaskForm, TaskEditForm
import datetime

def home(request):
    """
    Display an individual home page.
    """
    if request.user.is_authenticated:
        return dashboard(request)
    else:
        return render(request, 'home.html')

def contact(request):
    '''
    Display contact page.
    '''
    return render(request, 'contact.html')

@login_required
def dashboard(request):
    """
    Display dashboard

    ``Task``
        An instance of Task Model.
    """
    results = Task.objects.all()
    nows = datetime.datetime.now()
    if request.method == 'POST':
        form = TaskForm(request.POST)
        if form.is_valid():
            new_task = form.save(commit=True)
            new_task.user = User.objects.get(username=request.user)
            new_task.save()
            return HttpResponseRedirect(reverse('core:home'))
    else:
        form = TaskForm()

    return render(request, 'dashboard.html', {'form': form, 'results': results, 'nows':nows})

@login_required
def edit_task(request, id):
    """
    Display edit task template.

    ``Task``
        An instance of Task Model.
    """
    task = get_object_or_404(Task, id=id)
    if request.method == 'POST':
        form = TaskEditForm(request.POST, instance=task)
        if form.is_valid():
            new_task = form.save(commit=True)
            new_task.user = User.objects.get(username=request.user)
            new_task.save()
            return HttpResponseRedirect(reverse('core:home'))
    else:
        form = TaskEditForm(instance=task)
    return render(request, 'edit_task.html', {'task': task, 'form': form})

@login_required
def delete_task(request, id):
    """
    Delete task by id.

    ``Task``
        An instance of Task Model.
    """
    task = get_object_or_404(Task, id=id)
    task.delete()
    return HttpResponseRedirect(reverse('core:dashboard'))


accounts/templates/base.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>TODO List</title>
<link rel="stylesheet" href="{% static 'css/pure-min.css' %}">
<link rel="stylesheet" href="{% static 'css/email.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'css/flatpickr.min.css' %}"/>
</head>
<body>
<div id="layout" class="content pure-g">
    <div id="nav" class="pure-u">
        <a href="#" class="nav-menu-button">Menu</a>
                    <div class="nav-inner">
            <button class="primary-button pure-button">TODO List</button>
            <div class="pure-menu">
                <ul class="pure-menu-list">                               
    {% if user.is_authenticated %}
        <li class="pure-menu-item"><a href="{% url 'core:dashboard' %}" class="pure-menu-link">Dashboard</a></li>
    {% else %}
        <li class="pure-menu-item"><a href="{% url 'core:home' %}" class="pure-menu-link">Home</a></li>
    {% endif %}
        <li class="pure-menu-item"><a href="{% url 'core:contact' %}" class="pure-menu-link">Contact</a></li>
    {% if user.is_authenticated %}
        <li class="pure-menu-item"><a href="{% url 'accounts:logout' %}" class="pure-menu-link">Sign Out</a></li>
    {% else %}
        <li class="pure-menu-item"><a href="{% url 'accounts:login' %}" class="pure-menu-link">Sign In</a></li>
    {% endif %}
                </ul>
            </div>
        </div>
    </div>
    {% block content %}
    {% endblock %}
</div>

<script src="{% static "js/yui-min.js" %}"></script>
<script src="{% static "js/jquery.js" %}"></script>
<script src="{% static "js/flatpickr.min.js" %}"></script>
<script>
    YUI().use('node-base', 'node-event-delegate', function (Y) {

        var menuButton = Y.one('.nav-menu-button'),
            nav        = Y.one('#nav');

        menuButton.on('click', function (e) {
            nav.toggleClass('active');
        });
        var example = flatpickr('#flatpickr', {
            dateFormat: 'm/d/Y',
            minDate: Date(),
        });

    });
</script>

</body>
</html>

core/templates/base.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>TODO List</title>
<link rel="stylesheet" href="{% static 'css/pure-min.css' %}">
<link rel="stylesheet" href="{% static 'css/email.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'css/flatpickr.min.css' %}"/>
</head>
<body>
<div id="layout" class="content pure-g">
    <div id="nav" class="pure-u">
        <a href="#" class="nav-menu-button">Menu</a>
                    <div class="nav-inner">
            <button class="primary-button pure-button">TODO List</button>
            <div class="pure-menu">
                <ul class="pure-menu-list">                               
    {% if user.is_authenticated %}
        <li class="pure-menu-item"><a href="{% url 'core:dashboard' %}" class="pure-menu-link">Dashboard</a></li>
    {% else %}
        <li class="pure-menu-item"><a href="{% url 'core:home' %}" class="pure-menu-link">Home</a></li>
    {% endif %}
        <li class="pure-menu-item"><a href="{% url 'core:contact' %}" class="pure-menu-link">Contact</a></li>
    {% if user.is_authenticated %}
        <li class="pure-menu-item"><a href="{% url 'accounts:logout' %}" class="pure-menu-link">Sign Out</a></li>
    {% else %}
        <li class="pure-menu-item"><a href="{% url 'accounts:login' %}" class="pure-menu-link">Sign In</a></li>
    {% endif %}
                </ul>
            </div>
        </div>
    </div>
    {% block content %}
    {% endblock %}
</div>

<script src="{% static "js/yui-min.js" %}"></script>
<script src="{% static "js/jquery.js" %}"></script>
<script src="{% static "js/flatpickr.min.js" %}"></script>
<script>
    YUI().use('node-base', 'node-event-delegate', function (Y) {

        var menuButton = Y.one('.nav-menu-button'),
            nav        = Y.one('#nav');

        menuButton.on('click', function (e) {
            nav.toggleClass('active');
        });
        var example = flatpickr('#flatpickr', {
            dateFormat: 'm/d/Y',
            minDate: Date(),
        });

    });
</script>

</body>
</html>

core/templates/contact.html
{% extends "base.html" %}

{% block content %}
<div class="pure-g-r content-ribbon">
    <div class="pure-u-1">
        <h1>Talk to us</h1>
        <p>
        You can contact us either by email as through social networks, follow the links below:
        </p>
        <h4>Links</h4>
        <ul>
            <li>E-mail: <a href="https://mail.mospolytech.ru/">https://mail.mospolytech.ru/</a></li>
            <li>Web: <a href="https://new.mospolytech.ru/">mospolytech</a></li>
            <li>Facebook: <a href="https://www.facebook.com/moscowpolytech/">mospolytech</a></li>
            <li>YouTube: <a href="https://www.youtube.com/channel/UCJMY2ilUHti99R6ii2PIIYA/videos">mospolytech</a></li>
        </ul>
    </div>
</div>
{% endblock %}

core/templates/dashboard.html
{% extends "base.html" %}
{% block content %}
<div id="list" class="pure-u-1">
<h1 style="text-align: center;">Your tasks</h1>
        <div class="email-item email-item-unread pure-g">
            <div class="pure-u"></div>
            <div class="pure-u-3-4">
            {% for result in results %}
                {% if result.user == user %}
                    {% if result.is_complete == False %}
                        {% if result.is_past_due %}
                        <h5 class="email-name"><span class="email-count-late">{{ result.due_date}}</span></h5>
                        {% else %}
                        <h5 class="email-name"><span class="email-count">{{ result.due_date}}</span></h5>
                        {% endif %}
                        <h4 class="email-subject">{{ result.title}}</h4>
                        <p class="email-desc">{{result.tags.names|join:", "}}</p>
                        <a class="email-desc" href="/dashboard/edit-task/{{result.id}}">✎</a>
                        <a class="email-exc" onclick="return confirm('You are about to delete: {{result.title}}. Do you wish to continue?')" href="/dashboard/delete-task/{{result.id}}">x</a>
                    {% endif %}
                {% endif %}
            {% endfor %}
            </div>
        </div>
    </div>
    <div id="main" class="pure-u-1">
        <div class="email-content">
            <div class="email-content-body">
                <div class="pure-u-1-2">
                    <form class="pure-form pure-form-stacked" action="." method="post">
                    {% csrf_token %}
                    <fieldset>
                    <div class="pure-control-group">
                        {{ form }}
                        <input type="hidden" name="user" value="{{ user.id }}">
                        <br>
                    </div>
                    </fieldset>
                    <button type="submit" class="pure-button pure-button-primary">Create Task</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

core/templates/edit_task.html
{% extends "base.html" %}
{% block content %}

<div id="main" class="pure-u-1">
        <div class="email-content">
            <div class="email-content-body">
                <div class="pure-u-1-2">
					<form class="pure-form pure-form-stacked" action="." method="post">{% csrf_token %}
					{{form}}
						<br><br>
						<button type="submit" class="pure-button pure-button-primary">Save Task</button>
						<a href="{%url 'core:home' %}" class="pure-button pure-button-secondary">Cancel</a>
					</form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

core/templates/home.html
{% extends "base.html" %}
{% block content %}
{% if user.is_authenticated %}
{% include "dashboard.html" %}
{% else %}
<div class="splash">
    <div class="pure-g-r">
        <div class="pure-u-1">
            <div class="l-box splash-text">
                <h1 class="splash-head">
                    Get productive! 
                </h1>
                <h2 class="splash-subhead">
                    This task manager will help you to get things done, finally.
                </h2>
                <p>
                    <a href="{% url 'accounts:register' %}" class="pure-button primary-button">Join us
                    </a>
                </p>
            </div>
        </div>
    </div>
</div>
<div class="pure-g-r content-ribbon">
    <div class="pure-u-2-3">
        <div class="l-box">
            <h4 class="content-subhead">Todo lists are fun!</h4>
            <h3>Organize your tasks</h3>
            <p>
                Just to do it lets you to organize your tasks accordingly, lets you filter by tags, warns you if I have a passed due date, and so on.
            </p>
        </div>
    </div>
</div>
{% endif %}
{% endblock %}

manager/templates/base.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>TODO List</title>
<link rel="stylesheet" href="{% static 'css/pure-min.css' %}">
<link rel="stylesheet" href="{% static 'css/email.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'css/flatpickr.min.css' %}"/>
</head>
<body>
<div id="layout" class="content pure-g">
    <div id="nav" class="pure-u">
        <a href="#" class="nav-menu-button">Menu</a>
                    <div class="nav-inner">
            <button class="primary-button pure-button">TODO List</button>
            <div class="pure-menu">
                <ul class="pure-menu-list">                               
    {% if user.is_authenticated %}
        <li class="pure-menu-item"><a href="{% url 'core:dashboard' %}" class="pure-menu-link">Dashboard</a></li>
    {% else %}
        <li class="pure-menu-item"><a href="{% url 'core:home' %}" class="pure-menu-link">Home</a></li>
    {% endif %}
        <li class="pure-menu-item"><a href="{% url 'core:contact' %}" class="pure-menu-link">Contact</a></li>
    {% if user.is_authenticated %}
        <li class="pure-menu-item"><a href="{% url 'accounts:logout' %}" class="pure-menu-link">Sign Out</a></li>
    {% else %}
        <li class="pure-menu-item"><a href="{% url 'accounts:login' %}" class="pure-menu-link">Sign In</a></li>
    {% endif %}
                </ul>
            </div>
        </div>
    </div>
    {% block content %}
    {% endblock %}
</div>

<script src="{% static "js/yui-min.js" %}"></script>
<script src="{% static "js/jquery.js" %}"></script>
<script src="{% static "js/flatpickr.min.js" %}"></script>
<script>
    YUI().use('node-base', 'node-event-delegate', function (Y) {

        var menuButton = Y.one('.nav-menu-button'),
            nav        = Y.one('#nav');

        menuButton.on('click', function (e) {
            nav.toggleClass('active');
        });
        var example = flatpickr('#flatpickr', {
            dateFormat: 'm/d/Y',
            minDate: Date(),
        });

    });
</script>

</body>
</html>